### ISSUE TITLE
Possible SQL Injection

### ISSUE THREAD

**Issue by ambravo** [figaf/SAPPItoJDBC#2]
Hi Figaf,

I believe the code is susceptible to SQL Injection. For instance, if the table name contains a crafted statement, this line could generate a malicious select:
https://github.com/figaf/SAPPItoJDBC/blob/58db7d84bef36cab6f2556443a903b34a43c2091/src/main/java/com/figaf/saptojdbc/saptojdbc/web/RunQueryParser.java#L103

Long shot, but still a possibility. Thanks for make this open source!

Ariel

**Comment by dgraversen** [comment]
Thanks the bug. Yes probably not optimal. 
Yes concatenating SQL strings is not really a good idea. 
We do also support the SQL Query where you can create any Query you like.
